#!/usr/bin/with-contenv bash
# shellcheck shell=bash

install -d -m 700 /etc/ssh/hostkeys
for key_type in ed25519 ecdsa rsa; do
    key_file="/etc/ssh/hostkeys/ssh_host_${key_type}_key"
    if [ ! -f "$key_file" ]; then
        ssh-keygen -q -t "$key_type" -f "$key_file" -N ''
    fi
done

exec 2>&1 \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${LISTEN_PORT:-2222}" \
        /usr/sbin/sshd -D -e
