name: Build Container

on:
  push:
    branches:
    - master
    tags:
    - "**"

permissions:
  packages: write
  contents: write

jobs:
  build_docker:
    name: build docker
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set build env
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/no_trainer_client:latest
            ghcr.io/${{ env.GHCR_OWNER }}/no_trainer_client:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

